import Head from "next/head";
import styles from "../../styles/Layout.module.css";
import Footer from "./footer";
import Header from "./header";
import { motion } from "framer-motion";

export default function Layout({ children, title }) {
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className={styles.layoutContainer}>
      <Head>
        <title>Llewellyn - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{delay: 0.5}} className={styles.contentContainer}>{children}</motion.div>
      <Footer />
    </motion.div>
  );
}
