import Head from "next/head";
import styles from "../../styles/Layout.module.css";
import Footer from "./footer";
import Header from "./header";

export default function Layout({ children, title }) {
  return (
    <div className={styles.layoutContainer}>
      <Head>
        <title>Llewellyn - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.contentContainer}>{children}</div>
      <Footer />
    </div>
  );
}
